version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: forumhub_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: forumhub
      MYSQL_USER: forumhubuser
      MYSQL_PASSWORD: forumhubpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: